[http.routers]
[http.routers.jellyfin-rtr]
entryPoints = ["https"]
middlewares = ["chain-oauth"]
rule = "Host(`jellyfin.example.com`)"
service = "jellyfin-svc"

[http.routers.jellyfin-rtr.tls]
certresolver = "dns-cloudflare"

[http]
[http.services]
[http.services.jellyfin-svc]

[[http.services.jellyfin-svc.loadBalancer.servers]]
url = "http://192.168.x.xxx:8096" # Remember to update to yor local-ip
