http:
  routers:
    pihole-rtr:
      rule: 'Host(`pihole.{{env "DOMAINNAME_CLOUD_SERVER"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-oauth
      service: pihole-svc
      tls:
        certResolver: dns-cloudflare
  services:
    pihole-svc:
      loadBalancer:
        servers:
          - url: "http://INSERT_YOUR_LOCAL_IP_HERE:80"
